routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ArticleController@index');

Route::resource('article','ArticleController');
Route::resource('comment', 'CommentController')->except(['index','show','create']);
Route::post('rating','RatingController@store')->name('add-rating');
Route::get('user','UserPageController@index')->name('user-page');
Route::get('admin','AdminPageController@index')->name('admin-page');
Route::put('set-date/{id}','AdminPageController@update')->name('article-publish');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title',
        'body',
        'publish_date',
        'user_id',
        'category_id',
        'tag_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function tag()
    {
        return $this->belongsTo(Tag::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function rating()
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use App\Http\Requests\ArticleRequest;
use App\Tag;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $articles = Article::where('publish_date','<=',Carbon::today())->paginate(6);
        return view('article.index',compact('articles'));
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('article.create',compact('categories','tags'));
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ArticleRequest $request)
    {
        $article = new Article($request->all());
        $article->user_id = $request->user()->id;
        $article->save();
        return redirect(route('article.index'))->with('status',"{$article->title} has created!");
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $article = Article::findOrfail($id);
        $user = $article->user->id;
        $find_user = User::findorFail($user);
        $count_articles = $find_user->articles->count();
        $quality = $article->rating->sum('quality');
        $actual = $article->rating->sum('actual');
        $rating = ($count_articles + $quality + $actual) / 3;
        return view('article.show',compact('article','rating'));
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit($id)
    {
        $article = Article::findOrfail($id);
        $this->authorize('edit',$article);
        $categories = Category::all();
        $tags = Tag::all();
        return view('article.edit',compact('article','categories','tags'));
    }


    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(ArticleRequest $request, $id)
    {
        $article = Article::findOrfail($id);
        $article->update($request->all());
        return redirect(route('article.index'))->with('status',"{$article->title} has updated!");
    }


    public function destroy($id)
    {
        $article = Article::findOrfail($id);
        $this->authorize('destroy',$article);
        $article->delete();
        return redirect(route('article.index'))->with('status',"{$article->title} has deleted!");
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')
@section('content')
    <h1>create</h1>
    <form method="post" action="{{route('article.store')}}">
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
        </div>
        @error('title')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="category">Category</label>
            <select class="custom-select" id="category" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->title}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="tag">Tag</label>
            <select class="custom-select" id="tag" name="tag_id">
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->title}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
        </div>
        @error('body')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1>Edit</h1>
    <form method="post" action="{{route('article.update',$article)}}">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input value="{{$article->title}}" type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
        </div>
        @error('title')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="category">Category</label>
            <select class="custom-select" id="category" name="category_id">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->title}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="tag">Tag</label>
            <select class="custom-select" id="tag" name="tag_id">
                @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->title}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3">{{$article->body}}</textarea>
        </div>
        @error('body')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/article/index.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="padding-top: 50px;">Articles</h1>
    <button type="button" class="btn btn-secondary"><a style="color: white;" href="{{route('article.create')}}">Create Article</a></button>
    <div class="row">
    @foreach($articles as $article)
        <div class="card" style="width: 18rem; margin: 20px;">
            <div class="card-body">
                <h5 class="card-title"><a href="{{route('article.show',$article->id)}}">{{$article->title}}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{$article->category->title}}</h6>
                <p class="card-text">{{$article->body}}</p>
                <h6 class="card-subtitle mb-2 text-muted">Publish: {{$article->publish_date}}</h6>
                <div class="d-flex justify-content-between">
                    @can('edit',$article)
                <a href="{{route('article.edit',$article->id)}}"  class="card-link">Edit</a>
                    @endcan
                        @can('destroy',$article)
                <form style="margin-left: 20px;" method="post" action="{{route('article.destroy',$article)}}">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                            @endcan
                </div>
            </div>
        </div>
    @endforeach
    </div>
    <div class="row p-5">
        <div class="col-12 offset-4">
            {{$articles->links()}}
        </div>
    </div>
    </div>
    @endsection

resources/views/article/show.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top:50px; text-align: center;">{{$article->title}}</h1>
    <div class="jumbotron">
        <h3>Author: {{$article->user->name}}</h3>
        <p class="lead">{{$article->body}}</p>
        <h5>News rating: {{number_format($rating,2)}}</h5>
        <form method="post" action="{{route('add-rating')}}">
            @csrf
            <h4 style="margin-top: 40px;">Send Feedback</h4>
            <input type="hidden" name="user_id" value="{{$article->user->id}}">
            <input type="hidden" name="article_id" value="{{$article->id}}">
        <div class="d-flex justify-content-between">
            <div class="form-group">
                <label for="quality">Quality</label>
                <select name="quality" class="form-control" id="quality">
                    <option value="{{0}}">Select quality</option>
                    <option value="{{1}}">High</option>
                    <option value="{{-1}}">low</option>
                </select>
                <div class="form-group">
                    <label for="actual">Actual</label>
                    <select class="form-control"  name="actual" id="actual">
                        <option value="{{0}}">Select actual</option>
                        <option value="{{1}}">Actual</option>
                        <option value="{{-1}}">Not actual</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="happy_unhappy">how's the news</label>
                    <select class="form-control" name="happy_unhappy" id="happy_unhappy">
                        <option>how's the news</option>
                        <option value="happy">Happy</option>
                        <option value="unhappy">Unhappy</option>
                    </select>
                </div>
            </div>
        </div>
            <button style="margin-bottom: 20px;" class="btn-primary" type="submit">Send</button>
        </form>
    </div>

    <button style="margin-top: 10px;" class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment" aria-expanded="false" aria-controls="collapseExample">
        Comments
    </button>
    @foreach($article->comments as $comment)
        <div class="collapse comment" id="comment">
            <div style="margin-top: 10px" class="card card-body">
                <h4>{{$comment->user->name}}</h4>
                {{$comment->body}}
                <div class="d-flex justify-content-between">
                    @can('edit',$comment)
                        <a style="width: 100px; margin-top: 5px" class="btn btn-primary" href="{{route('comment.edit',$comment->id)}}">edit</a>
                    @endcan
                @can('delete',$comment)
                    <form  method="post"  action="{{ route('comment.destroy',$comment->id) }}">
                        @method('DELETE')
                        @csrf
                        <button class="like btn-danger" type="submit">delete</button>
                    </form>
                @endcan
                </div>
            </div>
        </div>
    @endforeach
    <form method="post" action="{{route('comment.store')}}">
        @csrf
        <input type="hidden" name="article_id" value="{{$article->id}}">
        <div class="form-group">
            <label for="comment">Enter comment</label>
            <textarea name="body" class="form-control @error('body') is-invalid @enderror" id="comment" rows="3"></textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button style="margin-bottom: 20px;" class="btn-primary" type="submit">Send</button>
    </form>
    @endsection